version: '3.8'

services:
  # Our Avax data extractor application
  avax-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Porta principal da aplicação para acesso local e pelo ngrok
    env_file:
      - .env.docker
    networks:
      - avax_dev_network
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    depends_on:
      - avax-extractor
    environment:
      # Você precisará adicionar NGROK_AUTHTOKEN ao seu arquivo .env.docker
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: ["http", "avax-extractor:8081", "--log=stdout"]
    ports:
      - "4040:4040"  # Porta para a UI web do Ngrok
    networks:
      - avax_dev_network

networks:
  avax_dev_network:
    driver: bridge 